{{- if .Values.prometheus.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ .Release.Name }}-services
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tagent.labels" . | nindent 4 }}
    app.kubernetes.io/component: metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ .Release.Name }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
{{- end }}
